services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    restart: unless-stopped
    ports:
      - "8337:8337"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /media/nas-hdd/nas-migration-backup-20260506/AppData/beets/config:/config
      - /media/nas-hdd/Musics:/music
      - /media/nas-hdd/Evyy Musics:/evymusics
